name: concurrency-test-multi

concurrency:
  group: workflow-example-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:

  example_job_1:
    runs-on: ubuntu-latest

    steps:

      - name: Generate job 1 activity
        run: |
          echo "Starting job 1"
          echo $(date +"%Y-%m-%d %H:%M:%S")
          # Initialize the counter
          counter=1

          # Start the while loop
          while [ $counter -le 10 ]
          do
            echo "Counter: $counter"
            ((counter++))  # Increment the counter by 1
            sleep 3
          done

          echo "job 1 completed"

  example_job_2:
    runs-on: ubuntu-latest
    needs: example_job_1

    steps:

      - name: Generate job 2 activity
        run: |
          echo "Starting job 2"
          echo $(date +"%Y-%m-%d %H:%M:%S")
          # Initialize the counter
          counter=1

          # Start the while loop
          while [ $counter -le 10 ]
          do
            echo "Counter: $counter"
            ((counter++))  # Increment the counter by 1
            sleep 3
          done

          echo "job 2 completed"

  example_job_3:
    runs-on: ubuntu-latest
    needs: example_job_2

    steps:

      - name: Generate job 3 activity
        run: |
          echo "Starting job 3"
          echo $(date +"%Y-%m-%d %H:%M:%S")
          # Initialize the counter
          counter=1

          # Start the while loop
          while [ $counter -le 10 ]
          do
            echo "Counter: $counter"
            ((counter++))  # Increment the counter by 1
            sleep 3
          done

          echo "job 3 completed"
