name: "Format Code: ensure code formatting guidelines are met"
on:
  workflow_dispatch: null
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  format-code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
 
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository }}

      - name: Generate a change in a file and create a new commit from it
        run: |
          echo "this is a new line"
  

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: mikereiddigital/test/code-formatter@main #using default for testing here
        with:
            ignore-files: "README.md"
            secret-token: ${{ secrets.GITHUB_TOKEN }}