name: Test GH 3

on:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:

  test:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read
      repository-projects: read
 
    steps:

      - name: output some text
        run: echo "hello world"
